// ABOUTME: Tests for the report generator, specifically generateChangesDoc().
// ABOUTME: Verifies the compact API changes doc format, section presence, and line limits.

import { generateChangesDoc, generateMarkdown } from '../report.js';
import type { DriftReport, OaiEndpoint, ParamDef, ToolParamDrift, ChangelogEntry } from '../types.js';

function makeParam(name: string, overrides: Partial<ParamDef> = {}): ParamDef {
  return {
    name,
    in: 'body',
    required: false,
    type: 'string',
    description: `The ${name} parameter`,
    ...overrides,
  };
}

function makeToolDrift(toolName: string, params: string[]): ToolParamDrift {
  return {
    toolName,
    toolFile: `${toolName.replace(/_/g, '-')}.ts`,
    endpoint: `api:post:/${toolName}`,
    newParams: params.map(p => makeParam(p)),
    removedParams: [],
    suggestedAction: 'Add missing params to Zod schema',
  };
}

function makeEndpoint(overrides: Partial<OaiEndpoint> = {}): OaiEndpoint {
  return {
    domain: 'twilio_api_v2010',
    path: '/test',
    method: 'get',
    operationId: 'TestOp',
    summary: 'Test endpoint',
    deprecated: false,
    parameters: [],
    requestBody: [],
    ...overrides,
  };
}

function makeReport(overrides: Partial<DriftReport> = {}): DriftReport {
  return {
    oaiVersion: '2.6.4',
    previousVersion: '2.6.3',
    generatedAt: '2026-02-19T10:00:00Z',
    cliVersion: '6.2.4',
    sdkVersion: '5.12.2',
    sdkPinned: '^5.0.0',
    newEndpoints: [],
    removedEndpoints: [],
    parameterChanges: [],
    breakingChanges: [],
    coverage: {
      totalOaiEndpoints: 794,
      mappedEndpoints: 220,
      mappedTools: 272,
      unmappedEndpoints: [],
      toolsWithParamDrift: [],
      coveragePercent: 27.7,
      domainCoverage: {
        twilio_api_v2010: { total: 200, mapped: 80, percent: 40 },
        messaging_v1: { total: 50, mapped: 15, percent: 30 },
      },
    },
    summary: {
      totalEndpoints: 794,
      newCount: 0,
      removedCount: 0,
      paramChangedCount: 0,
      breakingCount: 0,
      coveragePercent: 27.7,
    },
    ...overrides,
  };
}

describe('generateChangesDoc', () => {
  test('produces expected sections', () => {
    const doc = generateChangesDoc(makeReport());
    expect(doc).toContain('# Twilio API Changes');
    expect(doc).toContain('## Current Status');
    expect(doc).toContain('## Breaking Changes');
    expect(doc).toContain('## New Parameters for Existing Tools');
    expect(doc).toContain('## New Endpoints in Covered Domains');
    expect(doc).toContain('Auto-generated by api-sync pipeline');
  });

  test('stays under 150 lines with no drift', () => {
    const doc = generateChangesDoc(makeReport());
    const lineCount = doc.split('\n').length;
    expect(lineCount).toBeLessThan(150);
  });

  test('includes version metadata in header comment', () => {
    const doc = generateChangesDoc(makeReport());
    expect(doc).toContain('OAI: 2.6.4');
    expect(doc).toContain('SDK: 5.12.2');
    expect(doc).toContain('CLI: 6.2.4');
    expect(doc).toContain('Last updated: 2026-02-19');
  });

  test('shows SDK compatibility status', () => {
    const compatDoc = generateChangesDoc(makeReport({ sdkVersion: '5.12.2', sdkPinned: '^5.0.0' }));
    expect(compatDoc).toContain('✅');

    const mismatchDoc = generateChangesDoc(makeReport({ sdkVersion: '6.0.0', sdkPinned: '^5.0.0' }));
    expect(mismatchDoc).toContain('⚠️ MAJOR MISMATCH');
  });

  test('renders breaking changes when present', () => {
    const breaking: ChangelogEntry[] = [
      { version: '2.6.4', date: '2026-02-18', domain: 'messaging_v1', description: 'Removed legacy Send endpoint', isBreaking: true },
    ];
    const doc = generateChangesDoc(makeReport({ breakingChanges: breaking }));
    expect(doc).toContain('**messaging_v1**');
    expect(doc).toContain('Removed legacy Send endpoint');
    expect(doc).not.toContain('None since last sync');
  });

  test('shows "None since last sync" when no breaking changes', () => {
    const doc = generateChangesDoc(makeReport());
    expect(doc).toContain('None since last sync');
  });

  test('renders parameter drift table', () => {
    const drift = [
      makeToolDrift('send_sms', ['contentVariables', 'contentRetention']),
      makeToolDrift('make_call', ['machineDetection']),
    ];
    const doc = generateChangesDoc(makeReport({
      coverage: {
        ...makeReport().coverage,
        toolsWithParamDrift: drift,
      },
    }));
    expect(doc).toContain('| send_sms |');
    expect(doc).toContain('| make_call |');
    expect(doc).toContain('contentVariables');
    expect(doc).toContain('| 2 |');
    expect(doc).toContain('| 1 |');
  });

  test('limits parameter drift table to 20 entries', () => {
    const drift: ToolParamDrift[] = [];
    for (let i = 0; i < 25; i++) {
      drift.push(makeToolDrift(`tool_${i}`, [`param_${i}`]));
    }
    const doc = generateChangesDoc(makeReport({
      coverage: { ...makeReport().coverage, toolsWithParamDrift: drift },
    }));

    // Should show first 20 and a truncation note
    expect(doc).toContain('...and 5 more tools with parameter drift');
    // Still under 150 lines
    expect(doc.split('\n').length).toBeLessThan(150);
  });

  test('only shows new endpoints from covered domains', () => {
    const newEndpoints = [
      makeEndpoint({ domain: 'twilio_api_v2010', path: '/new-resource', method: 'post', summary: 'New covered endpoint' }),
      makeEndpoint({ domain: 'uncovered_domain', path: '/ignored', method: 'get', summary: 'Uncovered domain endpoint' }),
    ];
    const doc = generateChangesDoc(makeReport({ newEndpoints }));
    expect(doc).toContain('/new-resource');
    expect(doc).not.toContain('/ignored');
    expect(doc).not.toContain('uncovered_domain');
  });

  test('shows "None" when no new endpoints in covered domains', () => {
    const doc = generateChangesDoc(makeReport());
    // Check the New Endpoints section says "None."
    const newEndpointsSection = doc.split('## New Endpoints in Covered Domains')[1];
    expect(newEndpointsSection).toContain('None.');
  });

  test('shows "All MCP tools are in sync" when no param drift', () => {
    const doc = generateChangesDoc(makeReport());
    expect(doc).toContain('All MCP tools are in sync');
  });
});

describe('generateMarkdown', () => {
  test('produces expected header', () => {
    const md = generateMarkdown(makeReport());
    expect(md).toContain('# Twilio API Drift Report');
    expect(md).toContain('OAI Version');
  });
});
